[mgr]
show_hidden = true
[opener]
nvim = [
	{ run = "nvim %s", block = true }
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]
[open]
prepend_rules = [
	{ url = "*.zip", use = "extract" },
	{ url = "*.7z", use = "extract" },
	{ url = "*", use = "nvim" },
]

